[tool.poetry]
name = "practical-rag"
version = "0.1.0"
description = ""
authors = ["Tu Nguyen"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.5"
llama-index = "^0.8.68"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
